#!/usr/bin/perl
# Script used to organize IMA files generated by MRI

use strict;
use warnings;

# Get list of IMA files in tmp
my @TMPFILES = split(/\n/, `find /cnc/DATA/tmp -type f | grep .dcm`);

# Print the number of files in TMPFILES
my $num_files = scalar @TMPFILES;
print "Number of IMA files: $num_files\n";

# Define the output file name
my $output_file = "ima_files_list.txt";

# Open the output file for writing
open(my $fh, '>', $output_file) or die "Could not open file '$output_file' $!";

# Print each file name to the output file
foreach my $file (@TMPFILES) {
    print $fh "$file\n";
}

# Close the file handle
close($fh);
