#!/usr/bin/perl
# Script used to organize IMA files generated by MRI

use strict;
use warnings;

# Get list of IMA files in tmp
my @TMPFILES = split(/\n/, `find /cnc/DATA/tmp -type f | grep .dcm`);

# Print the number of files in TMPFILES
my $num_files = scalar @TMPFILES;
print "Number of IMA files: $num_files\n";

# Optional: Print the list of files
# Uncomment the following lines if you want to see the list of files
# foreach my $file (@TMPFILES) {
#     print "$file\n";
# }
